name: SlapperPlus
main: jojoe77777\SlapperPlus\Main
version: 2.0.2
api: [3.0.0]
author: jojoe77777
description: Add-on plugin for Slapper
depend: [Slapper, FormAPI]
website: "https://github.com/jojoe77777/SlapperPlus"

permissions:
  slapperplus.command:
    default: op
    description: "Allows access to /slapperplus"
