name: SlapperPlus
main: jojoe77777\SlapperPlus\Main
version: 1.1.0
api: 3.13.0
author: jojoe77777
description: Add-on plugin for Slapper
depend: Slapper
website: "https://github.com/jojoe77777/SlapperPlus"

permissions:
  slapperplus.command:
    default: op
    description: "Allows access to /slapperplus"
